# This file is machine-generated - editing it directly is not advised

[[LibFEM]]
git-tree-sha1 = "32eed615c055ff92d4b0675d541d7d85518c3b8e"
repo-rev = "master"
repo-url = "https://github.com/amdeld/LibFEM.jl"
uuid = "3625dbae-1167-4e4e-9595-224d0cceb916"
version = "0.1.0"
